### ISSUE TITLE
Inconsistency in description and code

### ISSUE THREAD

**Issue by TzOk83** [whizzosoftware/SIO2Arduino#10]
In the description you state "wire the button so that when it is pressed it sends 5v to Arduino digital pin 3. Make sure you use a pull-up resistor as shown here", that is a non sense, as pull-up resistor keeps pin at 5V, until it is brought to GND by the switch (switch is active LOW). Example schematics shows a circuit with a pull-down resistor and switch wired to the Vcc (so switch is active HIGH). On the other hand, the code initializes the ATMega's internal pull-up resistors, while the buttons seem to be active LOW (so the button should short the Arduino GPIO pin to GND, and not to Vcc).

Pull-up resistor - keeps pin high (at Vcc), and is used with input active low,
pull-down resistor - keeps pin low (at GND), and is used with input active high.

**Comment by whizzosoftware** [comment]
Thanks for your comments. Have you tried it? The schematics and code reflect what worked for me but I am happy to correct anything that needs to be.

**Comment by TzOk83** [comment]
Yes, I have tried it, code clearly indicates, that the GPIO pin has an internal pull-up enabled:
`pinMode(PIN_SELECTOR, INPUT_PULLUP);`
...and that it is active LOW:
`if (digitalRead(PIN_SELECTOR) == LOW && millis() - lastSelectionPress > 250 && isSwitchPressed==false)`
...while linked example from Arduino Playground, shows a button active HIGH with an external pull-down resistor.

The code from GitHub is impossible to compile under current version of Arduino IDE, but I've made required changes, to make it compile. It also doesn't work with the current version of SD FAT library, but I've managed to find one that is compatible with the code...

**Comment by whizzosoftware** [comment]
Ok, thanks. I have updated the description to: "If you want a physical button to select disk images, make sure the SELECTOR_BUTTON define in config.h is uncommented and wire the button so that when it is pressed it shorts the Arduino digital pin 3 to GND."
